### ISSUE TITLE
Consider using lvgl v7.0.0

### ISSUE THREAD

**Issue by jakubclark** [rafaelcaricio/lvgl-rs#10]
lvgl [v7.0.0](https://github.com/lvgl/lvgl/releases/tag/v7.0.0) was recently released. It may be worth-while to upgrade to it, considering this project is still in it's early stages.

**Comment by rafaelcaricio** [comment]
Good idea, shouldn't be hard to do that right now. As I was working mostly on the internal design of the library itself. Only a few (button, label) widgets are implemented.

**Comment by rafaelcaricio** [comment]
I'm working on this.
