### ISSUE TITLE
Create example using WebAssembly

### ISSUE THREAD

**Issue by rafaelcaricio** [rafaelcaricio/lvgl-rs#15]
Create a WebAssembly demo app using the [web simulator](https://github.com/rahul-thakoor/embedded-graphics-web-simulator) of `embedded_graphics` library. It would be a great way to show the possibilities of `lvgl-rs` by compiling to WASM. The example can also be a quick start for many people.

**Comment by FloVanGH** [comment]
Does anyone managed to run it on WebAssembly? When I try to build it I get the following error:

```
_core/../lv_font/../lv_misc/lv_area.h:17:10: fatal error: 'string.h' file not found
  cargo:warning=#include <string.h>
```

**Comment by rafaelcaricio** [comment]
Hey @FloVanGH , I haven't tried yet. But I'd imagine that to compile to WebAssembly we would need to tweak our `build.rs` to handle cases like this one.

**Comment by FloVanGH** [comment]
If you can adjust the `build.rs` I can contribute an example 🙂.

**Comment by FloVanGH** [comment]
I want to add an lvgl example to my crate: https://codeberg.org/morph/canvas-display. I have also a working desktop example for an other crate https://codeberg.org/morph/raqote-display.

**Comment by rafaelcaricio** [comment]
@FloVanGH I can work on updating the `build.rs`, but I'm pretty tight on free time right now so I cannot compromise when I can do it. I hope to get some time to work on lvgl-rs soon.

**Comment by rafaelcaricio** [comment]
Awesome work, btw! :)

**Comment by FloVanGH** [comment]
> @FloVanGH I can work on updating the `build.rs`, but I'm pretty tight on free time right now so I cannot compromise when I can do it. I hope to get some time to work on lvgl-rs soon.

Ok I see. It's not urgent. But I hope you'll find some time. And I hope you can continue your work, it's really great 🙂.

**Comment by FloVanGH** [comment]
> Awesome work, btw! :)

Thank you 🙂

**Comment by rafaelcaricio** [comment]
I've tried that this weekend and didn't work yet.  I will continue trying to compile for the `wasm32-unknown-emscripten` target, that one may work (https://github.com/rustwasm/team/issues/291).

**Comment by FloVanGH** [comment]
Hey, ok thank you for your effort 🙂.

**Comment by rafaelcaricio** [comment]
@FloVanGH after many hours of trial and error, it's possible to compile lvgl-rs to WASM after those changes https://github.com/rafaelcaricio/lvgl-rs/pull/31

I have an example here: https://github.com/rafaelcaricio/lvgl-rs-wasm

**Comment by FloVanGH** [comment]
@rafaelcaricio that's awesome :-) . Thank you. I will create an example for `canvas-display`.

**Comment by rafaelcaricio** [comment]
@FloVanGH No problem! Let me know if it works for you in the browser. As I said, even though I managed to make the example project compile successfully, it panics when running in the browser for some strange reason.

**Comment by rafaelcaricio** [comment]
<img width="1792" alt="Screenshot" src="https://user-images.githubusercontent.com/107613/93810988-bc4cff00-fc4f-11ea-9cf0-8dbd470d07ce.png">
This is the error I get... :/

**Comment by FloVanGH** [comment]
Ok thank you. I will check it.

**Comment by rafaelcaricio** [comment]
@FloVanGH  I managed to make it work! 🥳  The example project is running here: https://rafaelcaricio.github.io/lvgl-rs-wasm/

Example code: https://github.com/rafaelcaricio/lvgl-rs-wasm

**Comment by FloVanGH** [comment]
🎉
