### ISSUE TITLE
Compatible displays

### ISSUE THREAD

**Issue by justinmoon** [rafaelcaricio/lvgl-rs#3]
Awesome project.

Which displays would you expect this project to work with?

**Comment by rafaelcaricio** [comment]
Thank you for the interest. I would like to make keep this project compatible with any hardware that is compatible with [embedded-graphics](https://docs.rs/embedded-graphics/). Basically, there is no restriction on which hardware display you can use, as long as the microcontroller the display is connected to can run Rust and you have access to the framebuffer.

**Comment by rafaelcaricio** [comment]
Closing this issue, as I think we covered the question. Please reopen if you still have any concerns.
