### ISSUE TITLE
Running the demos on macOS fails, when sdl2 is missing

### ISSUE THREAD

**Issue by rwbr** [rafaelcaricio/lvgl-rs#35]
I'm on macOS Big Sur 11.0.1. When I try to run one of the demos I get the following error message:

```
...

"-framework" "Security" "-lSDL2" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lSDL2
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `demo`.

To learn more, run the command again with --verbose.

```

To make the samples work I manually have to install sdl2 first by issuing the following command:

`brew install sdl2`

After that, the samples work on macOS too. Please update the README accordingly. Thank's.

**Comment by rafaelcaricio** [comment]
@rwbr Thank you for the suggestion. Do you want to open a PR for this? I would be happy to accept it. If not, that is fina as well. I will update when I get some time.

**Comment by rwbr** [comment]
Sure! I will update the documentation and open a PR when done.
