### ISSUE TITLE
failed to build lvgl-rs 0.4.0

### ISSUE THREAD

**Issue by Zuzuk-null** [rafaelcaricio/lvgl-rs#38]
https://docs.rs/crate/lvgl/0.4.0/builds

**Comment by rafaelcaricio** [comment]
Thank you for pointing that out. I need to look into that. 

It's failing because we need the environment variable `DEP_LV_CONFIG_PATH ` to be set.

**Comment by rafaelcaricio** [comment]
Still not working: https://docs.rs/crate/lvgl/0.5.1/builds/358614

**Comment by rafaelcaricio** [comment]
I need to investigate how docs.rs builds, apparently it's some custom way of getting the crate code. One option is to copy the examples `lv_conf.h` file to lvgl-sys just for this build. I might do that, as it is an easy win.

**Comment by rafaelcaricio** [comment]
Building https://docs.rs/lvgl/0.5.2/lvgl/
