### ISSUE TITLE
Write docs for the public interface

### ISSUE THREAD

**Issue by rafaelcaricio** [rafaelcaricio/lvgl-rs#42]
We need to write documentation for the public interface of lvgl-rs.

**Comment by nia-e** [comment]
Partially addressed in #51 but I assume more needs to be done before this is closed?

**Comment by rafaelcaricio** [comment]
I think we can close, I just did a quick doc generation on the #51 branch and looks pretty good for now.

**Comment by nia-e** [comment]
Alrighty! 🥳
