### ISSUE TITLE
Button callbacks

### ISSUE THREAD

**Issue by justinmoon** [rafaelcaricio/lvgl-rs#5]
How can I define a button "on-click" callback?

I'm trying to add a button example and [I'm stuck trying to type the callback to `lvgl_sys::lvgl_obj_set_event_cb`](https://github.com/justinmoon/lvgl-rs/blob/50105eb3dcb2cbcb8dfb4cf0427a199d861aa058/examples/button/src/main.rs#L42)

**Comment by justinmoon** [comment]
It seems like `lvgl_sys` wants the callback to be an `unsafe extern "C"` function, which doesn't really make sense if I'm providing this callback from Rust ...

**Comment by rafaelcaricio** [comment]
Hi @justinmoon,

It is flattering that you have interest in using lvgl-rs. I just wanted to tell you that this project is in the very early stages of development. I would really appreciate help of others, like you, to make push this project forward. Most things are still missing and I'm still pondering about how to handle the global state dependency in lvgl library rely.

**Comment by justinmoon** [comment]
No problem. I'll try to help out wherever I can.

**Comment by rafaelcaricio** [comment]
In general, I'm trying to follow the recommendations from those articles:
- http://adventures.michaelfbryan.com/posts/how-not-to-riir/
- https://kornel.ski/rust-sys-crate

**Comment by justinmoon** [comment]
Thanks for sharing. 

I'm trying to figure out how to get these event callbacks working. [This post](https://users.rust-lang.org/t/callback-based-c-ffi/26583/5) seems to explain roughly what is needed, but still working on it

**Comment by justinmoon** [comment]
On a related note, how were you able to get a button to look like this? 
![image](https://user-images.githubusercontent.com/4335621/82100064-75ae2d80-96ce-11ea-8368-63404e453bf9.png)

Mine look like this
![image](https://user-images.githubusercontent.com/4335621/82100169-b3ab5180-96ce-11ea-8711-665b46017fba.png)

**Comment by rafaelcaricio** [comment]
@justinmoon that screenshot was in an earlier version of the demo app, https://github.com/rafaelcaricio/lvgl-rs/blob/7bf1ac0cae3b1867b4687efaf1ccbd9e321df54b/examples/demo/src/main.rs I was using SDL directly.

**Comment by rafaelcaricio** [comment]
Hey @justinmoon , I just implemented a way to add event callbacks. So you can do things when buttons are clicked, hovered, etc. Please look the example:
```rust
let mut button = Button::new(&mut screen);
button.on_event(|this, event| {
    if let lvgl::Event::Clicked = event {
        println!("Clicked!");
    }
});
```
https://github.com/rafaelcaricio/lvgl-rs/blob/master/examples/bar.rs#L48-L52

**Comment by rafaelcaricio** [comment]
I will close this ticket now, as this is supported. If you have other questions. Please open other issue.
