### ISSUE TITLE
Add announcement in readme for project in early stages

### ISSUE THREAD

**Issue by rafaelcaricio** [rafaelcaricio/lvgl-rs#6]
We need to add to the README of lvgl-rs that this project is in it's early stages. Not ready for production use and unstable API.

**Comment by justinmoon** [comment]
Good idea. Solicit contributors, too.

**Comment by rafaelcaricio** [comment]
After giving some though about this topic, I think we can do better. I have included a new section in the README that will give a better impression and more detailed perspective of what we currently support: https://github.com/rafaelcaricio/lvgl-rs#feature-support

**Comment by rafaelcaricio** [comment]
I will write later a contributing section in the README. :)
