### ISSUE TITLE
Tracking issue for version bump to 0.6

### ISSUE THREAD

**Issue by nia-e** [rafaelcaricio/lvgl-rs#65]
What are the outstanding things to do before bumping to 0.6.0? #51 will be an API-breaking change and so a semver bump will be needed. What else should be added/fixed/reworked?
My ideas thus far:

- [x] Close #42 
- [x] Merge #51 
- [x] Merge #64 
- [x] Merge #67 <=> Close #66 
- [x] Close #69
- [x] Close #70 
- [x] Merge #76 <=> Close #43 

Maybe:
- [ ] Close #32 
- [ ] Close #68 <=> Close #24 
- [x] Merge #81 <=> Close #25

**Comment by rafaelcaricio** [comment]
@nia-e you might find interesting things to upstream from here https://github.com/nviennot/lvgl-rs/commits/master
Usage https://github.com/nviennot/turbo-resin/blob/main/src/ui/main_loop.rs

**Comment by nia-e** [comment]
Lovely, thanks! I'll try to work this into the next release then, especially the LVGL update. Might delay #64 more for this.

**Comment by nia-e** [comment]
Is there anything else worth doing before we publish 0.6.0? I took a look at #25 but it doesn't seem exceedingly urgent (might make the API a little neater I suppose, so I could do that). For #32, I don't have access to a Windows machine ~~and I'd rather not install malware on my laptop~~ so I'm unsure what I can do. #68 I'm not sure will even be too relevant anymore, between removing the need to call `init()` and not having to deal with the timer once #25 is done.

**Comment by nia-e** [comment]
I could write more docs, I suppose - especially on `Widget`s, since we only really have examples there right now.

**Comment by nia-e** [comment]
@rafaelcaricio can I bump to 0.6.0 and release? Or are there more things you'd like to see done first? A lot has been updated and other than #82 I don't foresee any real breaking changes happening soon (and that's still a ways off and will require a lot of discussion to get to a final, mergeable state)

**Comment by rafaelcaricio** [comment]
@nia-e go for it! ;)
